# One-to-Many and Many-to-Many Joins - Lab

## Introduction

In this lab, you'll practice your knowledge of one-to-many and many-to-many relationships!

## Objectives

You will be able to:
* Explain one-to-many and many-to-many joins as well as implications for the size of query results
* Query data using one-to-many and many-to-many joins

## One-to-Many and Many-to-Many Joins
<img src='images/Database-Schema.png' width="600">

## Connect to the Database

Include the relevant imports, then connect to the database located at `data.sqlite`.

In [1]:
# Your code here
import pandas as pd
import sqlite3

conn = sqlite3.Connection('data.sqlite')

## Employees and Their Offices (a One-to-One Join)

Select all of the employees including their first name and last name along with the city and state of the office that they work out of (if they have one). Include all employees and order them by their first name, then their last name.

In [3]:
# Your code here
q = '''
SELECT firstName, lastName, city, state
    FROM employees
    JOIN offices
        USING(officeCode)
    GROUP BY firstName, lastName
    
;
'''

pd.read_sql(q,conn)

   firstName   lastName           city       state
0       Andy     Fixter         Sydney
1    Anthony        Bow  San Francisco          CA
2      Barry      Jones         London
3      Diane     Murphy  San Francisco          CA
4   Foon Yue      Tseng            NYC          NY
5     George     Vanauf            NYC          NY
6     Gerard     Bondur          Paris
7     Gerard  Hernandez          Paris
8       Jeff   Firrelli  San Francisco          CA
9      Julie   Firrelli         Boston          MA
10     Larry       Bott         London
11    Leslie   Jennings  San Francisco          CA
12    Leslie   Thompson  San Francisco          CA
13      Loui     Bondur          Paris
14      Mami      Nishi          Tokyo  Chiyoda-Ku
15    Martin     Gerard          Paris
16      Mary  Patterson  San Francisco          CA
17    Pamela   Castillo          Paris
18     Peter      Marsh         Sydney
19     Steve  Patterson         Boston          MA
20       Tom       King         Sydney
21   William  Patterson         Sydney
22   Yoshimi       Kato          Tokyo  Chiyoda-Ku

## Customers and Their Orders (a One-to-Many Join)

Select all of the customer contacts (first and last names) along with details for each of the customers' order numbers, order dates, and statuses.

In [5]:
# Your code here
q = '''
SELECT contactFirstName, contactLastName, orderNumber, orderDate, status
    FROM customers
    JOIN orders
        USING(customerNumber)
    GROUP BY contactFirstName, contactLastName
;
'''

pd.read_sql(q,conn)

   contactFirstName contactLastName  orderNumber   orderDate   status
0            Adrian          Huxley        10139  2003-07-16  Shipped
1             Akiko       Shimamura        10258  2004-06-15  Shipped
2             Allen          Nelson        10147  2003-09-05  Shipped
3              Ann            Brown        10129  2003-06-12  Shipped
4              Anna          O'Hara        10148  2003-09-11  Shipped
..              ...             ...          ...         ...      ...
93            Wendy       Victorino        10217  2004-02-04  Shipped
94          William           Brown        10233  2004-03-29  Shipped
95             Wing           Huang        10143  2003-08-10  Shipped
96           Yoshi           Tamuri        10206  2003-12-05  Shipped
97               Yu            Choi        10242  2004-04-20  Shipped

[98 rows x 5 columns]

## Customers and Their Payments (Another One-to-Many Join)

Select all of the customer contacts (first and last names) along with details for each of the customers' payment amounts and date of payment. Sort these results in descending order by the payment amount.

In [7]:
# Your code here
q = '''
SELECT contactFirstName, contactLastName, amount, paymentDate
    FROM customers
    JOIN payments
        USING(customerNumber)
    ORDER BY amount DESC
;
'''

pd.read_sql(q,conn)

    contactFirstName contactLastName     amount paymentDate
0             Diego           Freyre  120166.58  2005-03-18
1             Diego           Freyre  116208.40  2004-12-31
2              Susan          Nelson  111654.40  2003-08-15
3               Eric       Natividad  105743.00  2003-12-26
4              Susan          Nelson  101244.59  2005-03-05
..               ...             ...        ...         ...
268          Carine          Schmitt    1676.14  2004-12-18
269         Pascale         Cartrain    1627.56  2003-04-19
270           Jonas       Bergulfsen    1491.38  2003-10-28
271         Pascale         Cartrain    1128.20  2003-08-22
272            Akiko       Shimamura     615.45  2005-05-18

[273 rows x 4 columns]

## Orders, Order Details, and Product Details (a Many-to-Many Join)

Select all of the customer contacts (first and last names) along with the product names, quantities, and date ordered for each of the customers and each of their orders. Sort these in descending order by the order date.

> Note: This will require joining 4 tables! This can be tricky! Give it a shot, and if you're still stuck, turn to the next section where you'll see how to write subqueries that can make complex queries such as this much simpler!

In [11]:
# Your code here
q = '''
SELECT contactFirstName, contactLastName, productName, quantityOrdered, orderNumber, orderDate
    FROM customers
    JOIN orders
        USING(customerNumber)
    JOIN orderDetails
        USING(orderNumber)
    JOIN products
        USING(productCode)
    ORDER BY orderDate DESC
;
'''
#noice
pd.read_sql(q,conn)

,contactFirstName,contactLastName,productName,quantityOrdered,orderNumber,orderDate
0,Janine,Labrune,1962 LanciaA Delta 16V,38,10425,2005-05-31
1,Janine,Labrune,1957 Chevy Pickup,33,10425,2005-05-31
2,Janine,Labrune,1998 Chrysler Plymouth Prowler,28,10425,2005-05-31
3,Janine,Labrune,1964 Mercedes Tour Bus,38,10425,2005-05-31
4,Janine,Labrune,1926 Ford Fire Engine,19,10425,2005-05-31
...,...,...,...,...,...,...
2991,Roland,Keitel,1938 Cadillac V-16 Presidential Limousine,46,10101,2003-01-09
2992,Dorothy,Young,1917 Grand Touring Sedan,30,10100,2003-01-06
2993,Dorothy,Young,1911 Ford Town Car,50,10100,2003-01-06
2994,Dorothy,Young,1932 Alfa Romeo 8C2300 Spider Sport,22,10100,2003-01-06
2995,Dorothy,Young,1936 Mercedes Benz 500k Roadster,49,10100,2003-01-06

## Summary

In this lab, you practiced your knowledge of one-to-many and many-to-many relationships!